# docker run \
# -e ACTIONS_RUNNER_DEBUG=true \
# -e RUN_LOCAL=true \
# -v /path/to/local/codebase:/tmp/lint \
# ghcr.io/super-linter/super-linter:latest

name: Lint all the codes

on:
    # run on any push to a PR branch
    pull_request:

# cancel any previously-started, yet still active runs of this workflow on the same branch
concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:
    super-lint:
        name: Super-Linter

        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set DEFAULT_BRANCH to PR target
              if: ${{ github.base_ref != '' }}
              run: |
                  # shellcheck disable=2086
                  echo "DEFAULT_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV
                  echo "this is a PR branch. Let's only lint the files that are changed against the target branch '${{ github.base_ref }}'"

            - name: Set DEFAULT_BRANCH to current branch
              if: ${{ github.base_ref == '' }}
              run: |
                  # shellcheck disable=2086
                  echo "DEFAULT_BRANCH=$(echo '${{ github.ref }}' | sed 's/refs\/heads\///')" >> $GITHUB_ENV
                  echo "this is just a branch push, not a PR."

            - name: Are we linting all files?
              run: |
                  echo VALIDATE_ALL_CODEBASE=${{ !contains(github.event_name, 'pull_request') }}

            - name: Lint Code Base
              uses: super-linter/super-linter/slim@v6.0.0
              env:
                  GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
                  DEFAULT_BRANCH: ${{ env.DEFAULT_BRANCH }}
                  VALIDATE_ALL_CODEBASE: ${{ !contains(github.event_name, 'pull_request') }}

                  VALIDATE_DOCKERFILE: false
                  VALIDATE_JSCPD: false
                  VALIDATE_SHELL_SHFMT: false
                  VALIDATE_EDITORCONFIG: false
                  VALIDATE_CHECKOV: false
                  KUBERNETES_KUBEVAL_OPTIONS: --ignore-missing-schemas --schema-location https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/
                  VALIDATE_PYTHON_PYLINT: false
                  VALIDATE_PYTHON_MYPY: false
